#!/bin/sh

if git diff-index --quiet HEAD --; then
    # There are no changes.
    make format

    if ! git diff-index --quiet HEAD --; then
        # There were formatting changes.
        echo 'Code was not properly formatted on push.'
        echo 'YAPF formatter has been run. Please review changes and commit.'
        exit 1
    else
        exit 0
    fi
else
    # There are changes.
    echo 'Working state must be clean to run formatting.'
    exit 1
fi
