{% set name = load_setup_py_data(setup_file='setup.py', from_recipe_dir=True).name %}
{% set version = load_setup_py_data(setup_file='setup.py', from_recipe_dir=True).version %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ./

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.4
    - requests >=2.21
  run:
    - python >=3.4
    - requests >=2.21

test:
  imports:
    - pyconll
    - pyconll.tree
    - pyconll.unit

about:
  home: "https://github.com/pyconll/pyconll"
  license: "MIT"
  license_family: "MIT"
  license_file: "{{ environ['RECIPE_DIR'] }}/LICENSE"
  summary: "Read and manipulate CoNLL files"
  description: "Read and manipulate CoNLL files"
  doc_url: "https://pyconll.readthedocs.io/en/stable/"
  dev_url: "https://github.com/pyconll/pyconll"

extra:
  recipe-maintainers:
    - matgrioni
