name: Pyconll Release to Conda
on:
  push

jobs:
  release:
    name: Release pyconll
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Setup Python 3.8.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.5
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
      - name: Install conda-build
        run: |
          conda install conda-build
      - name: Build and upload conda package
        run: |
          conda build --token ${{ secrets.CONDA_API_TOKEN}} -u matgrioni meta.yaml
