name: Pyconll Release to Conda
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  release:
    name: Release pyconll
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          python-version: '3.14'
      - name: Configure conda channels
        run: |
          conda config --add channels conda-forge
          conda config --add channels defaults
      - name: Install conda dependencies
        run: |
          conda install conda-build
          conda install conda-verify
          conda install anaconda-client
      - name: Build and upload conda package
        run: |
          conda build --token ${{ secrets.CONDA_API_TOKEN }} --user pyconll meta.yaml
