name: DI

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  datatest:
    name: Data Integration across UD
    runs-on: ubuntu-24.04
    steps:
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::881490118399:role/pyconll-di
          aws-region: us-east-1
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'
      - uses: actions/cache@v5
        with:
          path: tests/int/_corpora_cache/artifacts
          key: di-corpora-artifacts-${{ hashFiles('tests/int/corpora.py') }}
      - name: Run
        run: |
          pip install -r requirements.txt
          make datatest
