name: Pyconll Release to PyPi
on:
  workflow_dispatch:

jobs:
  build:
    name: Build pyconll
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.2.0
      - run: uv build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  release:
    name: Release pyconll
    runs-on: ubuntu-24.04
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/pyconll
    permissions:
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish packages from dist/*
        # Make sure the current git ref is tagged.
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.13.0
